using Novatic.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Novatic.Util
{
    public class LanguageConfigUtil
    {
        public static List<LanguageConfig> arrList = new List<LanguageConfig>()
        {
            new LanguageConfig(10001, 1, "novatic", "novatic", "lblNovatic"),
            new LanguageConfig(10002, 1, "Đăng ký", "Register", "lblDangKi"),
            new LanguageConfig(10003, 1, "Chuyên Đề", "TOPIC", "lblChuyenDe"),
            new LanguageConfig(10004, 1, "Video mới nhất", "Latest Video", "lblVideoMoiNhat"),
            new LanguageConfig(10005, 1, "Bài viết mới nhất", "The Latest", "lblBaiVietMoiNhat"),
            new LanguageConfig(10006, 1, "Xu hướng", "Trending Now", "lblXuHuong"),
            new LanguageConfig(10007, 1, "Bài viết phổ biến", "Popular posts", "lblBaiVietPhoBien"),
            new LanguageConfig(10008, 1, "Lượt xem", "Views", "lblLuotXem"),
            new LanguageConfig(10009, 1, "Bình luận", "Comments", "lblTitleBinhLuan"),
            new LanguageConfig(10010, 1, "Trả lời bình luận", "Leave a reply", "lblTraLoiBinhLuan"),
            new LanguageConfig(10011, 1, "Chia sẻ qua mạng xã hội", "Social connect", "lblChiaSeQuaMangXaHoi"),
            new LanguageConfig(10012, 1, "Địa chỉ email của bạn sẽ được bảo mật. Các trường * là bắt buộc", "Your email address will not be published. Required fields are marked *", "lblDiaChiEmailCuaBan"),
            new LanguageConfig(10013, 1, "Tên", "Name", "lblTen"),
            new LanguageConfig(10014, 1, "Email", "Email", "lblEmail"),
            new LanguageConfig(10015, 1, "Đăng bình luận", "Post Comment", "lblDangBinhLuan"),
            new LanguageConfig(10016, 1, "Xem thêm", "More in", "lblXemThem"),
            new LanguageConfig(10017, 1, "Xem tất cả", "View all", "lblXemHet"),
            new LanguageConfig(10018, 1, "Bởi", "By", "lblBoi"),
            new LanguageConfig(10019, 1, "Bài viết tương tự", "You may also like", "lblBaiVietTuongTu"),
            new LanguageConfig(10020, 1, "Đăng kí tài khoản", "Connect with us!", "lblDangKiNhanThongBao"),
            new LanguageConfig(10021, 1, "Nhập email của bạn để nhận bản tin của chúng tôi", "Enter your email to receive our newsletter.", "lblNhapEmailCuaBan"),
            new LanguageConfig(10022, 1, "Địa chỉ email của bạn", "Your email address", "lblDiaChiEmailCuaBanSubscribe"),
            new LanguageConfig(10023, 1, "Đừng lo lắng, chúng tôi sẽ không gửi thư rác", "Don't worry, we don't spam", "lblDungLoLang"),
            new LanguageConfig(10024, 1, "Đăng nhập", "Log In", "lblDangNhap"),
            new LanguageConfig(10025, 1, "Tên đăng nhập hoặc Email", "Username or Email", "lblTenDangNhap"),
            new LanguageConfig(10026, 1, "Mật khẩu", "Password", "lblMatKhau"),
            new LanguageConfig(10027, 1, "Lưu thông tin đăng nhập", "Remember Me", "lblLuuTaiKhoan"),
            new LanguageConfig(10028, 1, "Quên mật khẩu", "Lost your password?", "lblQuenMatKhau"),
            new LanguageConfig(10029, 1, "hoặc", "or", "lblHoac"),
            new LanguageConfig(10030, 1, "Đăng ký", "Sign up", "lblDangKy"),
            new LanguageConfig(10031, 1, "Đừng bỏ lỡ", "Do not miss", "lblDungBoLo"),
            new LanguageConfig(10032, 1, "Chuyên đề công nghệ mới", "Detailed reviews from our tech savvies.", "lblChuyenDeCongNghe"),
            new LanguageConfig(10033, 1, "Xem gì hôm nay", "What to watch for today", "lblXemGiHomNay"),
            new LanguageConfig(10034, 1, "Bài trước", "Previous article", "lblBaiTruoc"),
            new LanguageConfig(10035, 1, "Bài sau", "Next article", "lblBaiSau"),


            new LanguageConfig(10036, 1, "Thành Công", "Success", "lblThanhCong"),
            new LanguageConfig(10037, 1, "Bạn đã đăng ký nhận bản tin thành công!", "You have successfully subscribed to the newsletter.", "lblThanhCongDetail"),
            new LanguageConfig(10038, 1, "Lỗi", "Error", "lblError"),
            new LanguageConfig(10039, 1, "Bạn chưa nhập email. Vui lòng nhập email để nhận bản tin của chúng tôi!", "You have not entered your email. Please enter your email to receive our newsletter!", "lblErrorDetail"),
            new LanguageConfig(10040, 1, "Định dạng Email không hợp lệ!", "Incorrect email format!", "lblErrorEmailFormat"),
            new LanguageConfig(10041, 1, "Email của bạn đã đăng ký nhận bản tin", "Your email already exists!", "lblEmailAlreadyExists"),
            new LanguageConfig(10042, 1, "Đã đăng ký", "Already exists!", "lblAlreadyExists"),
            new LanguageConfig(10043, 1, "Vui lòng kiểm tra dữ liệu của bạn!", "Please check your data!", "lblCheckData"),

            new LanguageConfig(10044, 1, "Xem bài cũ hơn", "See older Posts", "lblXemBaiCuHon"),

            //multilanguage for head : tag page, search page,...
            new LanguageConfig(10044, 1, "Tổng có", "There are", "lblTongCo"),
            new LanguageConfig(10045, 1, "kết quả", "results", "lblKetQua"),

            //multilanguage for head : favourite page
            new LanguageConfig(10046, 1, "BÀI VIẾT YÊU THÍCH", "FAVOURITE POSTS", "lblBaiVietYeuThich"),
            new LanguageConfig(10046, 1, "BÀI VIẾT ĐÃ ĐỌC", "READED POSTS", "lblBaiVietDaDoc"),
            new LanguageConfig(10047, 1, "Số bài viết", "Posts number", "lblSoBaiViet"),

            // about us in Footer
            new LanguageConfig(10048,1,"Về chúng tôi","About us","lblVeChungToi"),
            new LanguageConfig(10049,1,
                "GappingWorld là trang thông tin nông sản toàn cầu,với mong muốn mang đến những thông tin cập nhật cho những người quan tâm đến diễn biến thị trường nông sản toàn cầu.",
                "GappingWorld is a global agricultural information site, with the desire to provide updates to those who are interested in global agricultural market developments.",
                "lblVeChungToi_NoiDung"),
            new LanguageConfig(10050,1,"Liên hệ","Contact","lblLienHe"),
            new LanguageConfig(10051,1,"Tin nhắn","Your Message","lblYourMessage"),
            new LanguageConfig(10052,1,"Chúng tôi là một nhóm các chuyên gia độc lập hoạt động trong khu vực nhà nước và khu vực tư nhân, cùng góp công sức để tạo nên một nguồn thông tin - dữ liệu đa dạng, có chiều sâu và đáng tin cậy về nông nghiệp Việt Nam - thế giới Mọi nhu cầu thông tin xin liên hệ thông qua email: ","We are a group of independent experts, working in the public and private sectors, working together to create a diverse, in-depth, reliable and informative field of Vietnam - global agriculture information. For any information please contact via email: ","lblNoiDungLienHe"),
            new LanguageConfig(10053,1,"Gửi tin nhắn","Send Message","lblSendMessage"),
            new LanguageConfig(10054,1,"Chưa là thành viên?","Not a member yet?","lblChuaLaThanhVien"),
            new LanguageConfig(10055,1,"Tham gia GAPPINGWORLD, các quyền lợi bao gồm:","Joining GAPPINGWORLD, benefits include:","lblQuyenLoiThamGia"),
            new LanguageConfig(10056,1,"THÀNH VIÊN KHÔNG TRẢ PHÍ","MEMBERS DO NOT PAY FEES","lblKhongTraPhi"),
            new LanguageConfig(10057,1,"Thành viên trả phí","Premium membership","lblThanhVienTraPhi"),
            new LanguageConfig(10058,1,"Lịch sử bài viết đã đọc trong 30 ngày gần nhất","History of the article read in the last 30 days","lblLichSuBaiViet"),
            new LanguageConfig(10059,1,"Ghim bài viết ưa thích","Pin favorite posts","lblGhimBaiVietYeuThich"),
            new LanguageConfig(10060,1,"Lưu trữ danh sách bình luận","Archive the list of comments","lblLuuTruBinhLuan"),
            new LanguageConfig(10061,1,"Tiếp cận 100% bài viết trên trang","Reach 100% of articles on the page","lblTiepCanBaiViet"),
            new LanguageConfig(10062,1,"Tìm kiếm nâng cao kho hình ảnh dữ liệu","Advanced search data warehouse image","lblTimKhoAnhDuLieu"),
            new LanguageConfig(10063,1,"Nhận Newsletter hàng tháng về các chủ đề được quan tâm nhiều nhất","Receive a monthly Newsletter on topics that are most interested in","lblNhanNewsLetter"),
            new LanguageConfig(10064,1,"Mức phí: 50.000 VNĐ/tháng","Fee: 50,000 VND / month","lblMucPhi"),
            new LanguageConfig(10065,1,"Hình thức thanh toán: Chuyển khoản hoặc Ví điện tử","Payment method: Bank transfer or E-wallet","lblHinhThucThanhToan"),
            new LanguageConfig(10070,1,"Khảo sát toàn diện","Survey Overview","lblKhaoSatToanDien"),
            new LanguageConfig(10071,1,"Tìm hiểu thêm","Research more infomation","lblTimHieuThem"),
            new LanguageConfig(10072,1,"Bạn chưa có tài khoản","Do not have an account","lblChuaCoTaiKhoan"),
            new LanguageConfig(10073,1,"Hãy đăng nhập là thành viên để trải nghiệm đầy đủ tính năng của sản phầm","Please login as a member to experience the full features of the product","lblHayDangNhapThanhVien"),
            new LanguageConfig(10074,1,"Nhập tên đăng nhập hoặc Email","Press username or email","lblNhapTenDangNhap"),
            new LanguageConfig(10075,1,"Nhập mật khẩu","Press password","lblNhapMatKhau"),
            new LanguageConfig(10076,1,"Hãy đăng nhập là thành viên để trải nghiệm đầy đủ tính năng của sản phầm","Please login as a member to experience the full features of the product","lblHayDangNhapThanhVien"),
            new LanguageConfig(10077,1,"Đăng ký tham gia","Registration","lblDangKyThamGia"),
            new LanguageConfig(10078,1,"ĐĂNG KÝ NHẬN HỖ TRỢ","REGISTER FOR SUPPORT","lblDangKyNhanHoTro"),
            new LanguageConfig(10079,1,"Kết nối với chúng tôi","Connect with us","lblKetNoiVoiChungToi"),
            new LanguageConfig(10080,1,"XEM TIẾP","NEXT","lblXemTiep"),
            new LanguageConfig(10081,1,"Đăng ký tài khoản","Sign up","lblDangKyTaiKhoan"),

            new LanguageConfig(10082,1,"Họ và tên","Full Name","lblHoVaTen"),
            new LanguageConfig(10083,1,"Địa chỉ Email","Email Address","lblDiaChiEmail"),
            new LanguageConfig(10084,1,"Nhập lại mật khẩu","Re-Enter the password","lblNhapLaiMatKhau"),
            new LanguageConfig(10085,1,"Nhập địa chỉ Email","Press Email Address","lblNhapEmail1"),
            new LanguageConfig(10086,1,"Bạn đã có tài khoản?","Do you already have an account?","lblDaCoTaiKhoan"),
            new LanguageConfig(10087,1,"Đăng ký là thành viên để trải nghiệm đầy đủ tính năng của sản phầm","Register as a member to experience the full features of the product","lblNoiDungDangKy"),
            new LanguageConfig(10088,1,"Tìm lại mật khẩu","Find your password","lblTimlaiMatKhau"),
            new LanguageConfig(10089,1,"Hãy nhập đầy đủ thông tin tài khoản để tìm lại mật khẩu của bạn","Please enter your full account information to find your password","lblNoiDungTimLaiMatKhau"),
            new LanguageConfig(10090,1,"XÁC NHẬN","CONFIRM","lblXacNhan"),
            new LanguageConfig(10091,1,"ĐỌC THÊM","READ MORE","lblDocThem"),
            new LanguageConfig(10092,1,"XEM DANH SÁCH SỰ KIỆN","SEE LIST OF EVENTS","lblXemThemDSSuKien"),
            new LanguageConfig(10093,1,"Quy định & Điều khoản","Terms & Conditions","lblQuyDinhVaDieuKhoan"),
            new LanguageConfig(10094,1,"Chính sách bảo mật","Privacy Policy","lblChinhSachBaoMat"),
            new LanguageConfig(10095,1,"Bản quyền thuộc Cục Phát triển doanh nghiệp","Copyright by Agency for Enterprise Development","lblBanQuyen"),
            new LanguageConfig(10096,1,"Trưởng Ban Biên tập: Nguyễn Như Sơn – Giám đốc Trung tâm Tin học; Email: banbientap@mpi.gov.vn Ghi rõ nguồn Cổng thông tin điện tử Bộ Kế hoạch và Đầu tư (www.mpi.gov.vn) khi trích dẫn lại tin từ địa chỉ này.","Head of the Editorial Board: Nguyen Nhu Son – Director of the Center for Informatics; Email: banbientap @mpi.gov.vn Specify the source of the website of the Ministry of Planning and Investment (www.mpi.gov.vn) when quoting information from this address.","lblThongTinNguoiSoHuu"),
            new LanguageConfig(10097,1,"Cục Phát triển Doanh nghiệp, Bộ Kế hoạch và Đầu tư Số 6B Hoàng Diệu, Ba Đình, Hà Nội","General Department of Enterprise Development, Ministry of Planning and Investment No. 6B Hoang Dieu, Ba Dinh, Hanoi","lblDiaChiChuSoHuu"),
            new LanguageConfig(10098,1,"Đào tạo trực tuyến","Live training","lblDaoTaoTrucTiep"),
            new LanguageConfig(10099,1,"Trang chủ","Home","lblTrangChu"),
            new LanguageConfig(10100,1,"Tin tức cập nhật","Update News","lblTinTucCapNhat"),
            new LanguageConfig(10101,1,"Tin tức","News","lblTinTuc"),
            new LanguageConfig(10102,1,"USAID HỖ TRỢ PHỤC HỒI CÁC DOANH NGHIỆP NHỎ VÀ VỪA VIỆT NAM TRONG COVID-19","USAID SUPPORTS VIETNAMESE SMALL AND MEDIUM ENTERPRISE POST COVID-19 BUSINESS RECOVERY","lblTextBannerHeader"),
            new LanguageConfig(10103,1,"Tin tức tổng hợp","General News","lblTinTongHop"),
            new LanguageConfig(10104,1,"Tin tức nổi bật","Hottest News","lblTinNongNhat"),
            new LanguageConfig(10105,1,"Bộ kế hoạch và đầu tư","Ministry of Planning and Investment","lblBoKeHoachVaDauTu"),
            new LanguageConfig(10106,1,"Thông tin tài khoản","Account Setting","lblThongTinTaiKhoan"),
            new LanguageConfig(10107,1,"GIỚI THIỆU VỀ DỰ ÁN","Project Introduction","lblGioiThieuDuAn"),
            new LanguageConfig(10108,1,"Sự kiện đã được tổ chức","Event Was Held","lblSuKienDaDuocToChuc"),
            new LanguageConfig(10109,1,"Đơn vị tư vấn trực tiếp cho doanh nghiệp","Direct Consulting Unit For Businesses","lblDonViTuVanTrucTiepChoDoanhNghiep"),
            new LanguageConfig(10110,1,"Tổ chức tài chính cam kết tham gia","Financial institutions commit to participate","lblToChucTaiChinhCamKetThamGia"),
            new LanguageConfig(10111,1,"Doanh nghiệp SME Đăng ký nhận tư vấn","SME Enterprise Sign up for a consultationt","lblDoangNghiepSMEDangKiNhanTuVan"),
            new LanguageConfig(10112,1,"Sự kiện sắp diễn ra","Upcoming Events","lblSuKienSapDienRa"),
            new LanguageConfig(10113,1,"Sự kiện đang diễn ra","Ongoing Events","lblSuKienDangDienRa"),
            new LanguageConfig(10114,1,"Sự kiện đã kết thúc","Event Ended","lblSuKienDaKetThuc"),
            new LanguageConfig(10115,1,"Ngày","Days","lblNgay"),
            new LanguageConfig(10116,1,"Giờ","Hours","lblGio"),
            new LanguageConfig(10117,1,"Phút","Minutes","lblPhut"),
            new LanguageConfig(10118,1,"Giây","Seconds","lblGiay"),
            new LanguageConfig(10119,1,"bản đồ tài chính","Financial Map","lblBanDoTaiChinh"),
            new LanguageConfig(10120,1,"Hỗ trợ doanh nghiệp trong hoạt động","Supporting businesses in","lblHotroDoanhNghiepTrongHoatDong"),
            new LanguageConfig(10121,1,"tìm kiếm nguồn tài chính","finding financial resources","lblTimKiemNguonTaiChinh"),
            new LanguageConfig(10122,1,"Một trong những khó khăn của các doanh nghiệp trong thời gian dịch bệnh Covid-19 diễn ra là tiếp cận với các nguồn vốn hỗ trợ của Chính phủ thông qua hệ thống ngân hàng, công ty tài chính, quỹ đầu tư, nguồn vốn hỗ trợ từ ngân sách... Các tổ chức này, hỗ trợ các doanh nghiệp trong việc vay vốn dựa trên hợp đồng cam kết sản lượng và nguồn hàng.","One of the difficulties faced by businesses during the Covid-19 epidemic is accessing the Government's support capital through the banking system, financial companies, investment funds, financial support sources, etc. support from the budget... These organizations, support businesses in borrowing capital based on contracts to commit to output and source of goods.","lblGioiThieuBanDoTaiChinh"),
            new LanguageConfig(10123,1,"Nghiên cứu chi tiết","detailed study","lblNghienCuuChiTiet"),
            new LanguageConfig(10124,1,"Ngân Hàng","Bank","lblNganHang"),
            new LanguageConfig(10125,1,"Tổ chức","Organization","lblToChuc"),
            new LanguageConfig(10126,1,"Quỹ đầu tư","investment Fund","lblQuyDauTu"),
            new LanguageConfig(10127,1,"Ngân Sách","Budget","lblNganSach"),
            new LanguageConfig(10128,1,"Đồng hành cùng doanh nghiệp","To accompany the business","lblDongHanhCungDoanhNghiep"),
            new LanguageConfig(10129,1,"Tin tức các chính sách tài chính chính thống","News of official financial policies","lblTinTucCacChinhSachTaiChinhChinhThong"),
            new LanguageConfig(10130,1,"Tin tức doanh nghiệp và tài chính","Business and financial news","lblTinTucDoanhNghiepVaTaiChinh"),
            new LanguageConfig(10131,1,"GIẢI PHÁP HỖ TRỢ","Support Solution","lblGiaiPhapHoTro"),
            new LanguageConfig(10132,1,"Công cụ đánh giá","Comprehensive","lblCongCuDanhGia"),
            new LanguageConfig(10133,1,"tình trạng tài chính toàn diện","financial health assessment tool","lblTinhTrangTaiChinhToanDien"),
            new LanguageConfig(10134,1,"Hỗ trợ các doanh nghiệp định hình được tình hình tài chính của bản thân và đưa ra giải pháp hợp lý","Helping businesses shape their own financial situation and come up with reasonable solutions","lblMoTaCongCuDanhGia"),
            new LanguageConfig(10135,1,"Thực hiện một bài khảo sát nhỏ để chúng tôi có thể hỗ trợ bạn tốt nhất","Take a small survey so we can best assist you","lblMoTaSurvey"),
            new LanguageConfig(10136,1,"Sự kiện","Events","lblSuKien"),
            new LanguageConfig(10137,1,"Tài liệu trực quan sinh động","Vivid visual documentation","lblTaiLieuTrucQuanSinhDong"),
            new LanguageConfig(10138,1,"Tìm kiếm thông tin mới nhất, giá trị nhất","Find the latest, most valuable information","lblTimKiemThongTinMoiNhat"),
            new LanguageConfig(10139,1,"Chuyên gia hàng đầu trong lĩnh vực chuyển đổi số","The leading expert in the field of digital transformation","lblChuyenGiaHangDauTrongLinhVucChuyenDoiSo"),
            new LanguageConfig(10140,1,"Tài chính vững chắc cho doanh nghiệp SMEs","Solid finance for SMEs","lblTaiChinhVungChacChoDoanhNghiepSME"),
            new LanguageConfig(10141,1,"Sơ đồ Website","SiteMap","lblSoDoWeb"),
            new LanguageConfig(10142,1,"Trong trường hợp chúng tôi yêu cầu thông tin cá nhân của bạn tuân thủ các nghĩa vụ pháp lý hoặc hợp đồng, thì việc cung cấp dữ liệu đó là bắt buộc: nếu dữ liệu đó không được cung cấp, thì chúng tôi sẽ không thể quản lý mối quan hệ hợp đồng của chúng tôi với bạn hoặc để đáp ứng các nghĩa vụ đặt ra cho chúng tôi . Trong tất cả các trường hợp khác, việc cung cấp thông tin cá nhân được yêu cầu là tùy chọn.","Where we require your personal information to comply with legal or contractual obligations, then provision of such data is mandatory: if such data is not provided, then we will not be able to manage our contractual relationship with you, or to meet obligations placed on us. In all other cases, provision of requested personal information is optional.","lblNoiDungWebsite1"),
            new LanguageConfig(10142,1,"Bạn cũng có quyền yêu cầu chúng tôi chuyển thông tin cá nhân của bạn (tức là chuyển ở định dạng có cấu trúc, được sử dụng phổ biến và máy có thể đọc được, cho bạn), xóa hoặc hạn chế xử lý thông tin đó. Bạn cũng có quyền phản đối một số quá trình xử lý dựa trên lợi ích hợp pháp của chúng tôi, chẳng hạn như lập hồ sơ mà chúng tôi thực hiện với mục đích tiếp thị trực tiếp và, khi chúng tôi đã yêu cầu bạn đồng ý xử lý dữ liệu của bạn, hãy rút lại sự đồng ý này vì hơn được mô tả đầy đủ dưới đây.","You are also entitled to ask us to port your personal information (i.e. to transfer in a structured, commonly used and machine-readable format, to you), to erase it, or restrict its processing. You also have rights to object to some processing that is based on our legitimate interests, such as profiling that we perform for the purposes of direct marketing, and, where we have asked for your consent to process your data, to withdraw this consent as more fully described below.","lblNoiDungWebsite2"),
            new LanguageConfig(10142,1,"Các quyền này bị giới hạn trong một số trường hợp - ví dụ: chúng tôi có thể chứng minh rằng chúng tôi có yêu cầu pháp lý để xử lý thông tin cá nhân của bạn. Trong một số trường hợp, điều này có nghĩa là chúng tôi có thể giữ lại một số dữ liệu ngay cả khi bạn rút lại sự đồng ý của mình.","These rights are limited in some situations – for example, we can demonstrate that we have a legal requirement to process your personal information. In some instances, this means that we may retain some data even if you withdraw your consent.","lblNoiDungWebsite3"),
            new LanguageConfig(10165,1,"Sắp xếp theo","Order by","lblSapXepTheo"),
            new LanguageConfig(10166,1,"Tăng dần","Increase","lblTangDan"),
            new LanguageConfig(10167,1,"Giảm dần","Decrease","lblGiamDan"),
            new LanguageConfig(10168,1,"Nội dung chi tiết","Detail","lblNoiDungChiTiet"),
            new LanguageConfig(10169,1,"Sự kiện khác","More event","lblSuKienKhac"),
            new LanguageConfig(10170,1,"Tài liệu khác","More document","lblTaiLieuKhac"),
            new LanguageConfig(10173,1,"Xem lịch sử đánh giá","Review old survey","lblXemLichSuDanhGia"),
            new LanguageConfig(10174,1,"Thực hiện đánh giá","Do survey","lblThucHienDanhGia"),
            new LanguageConfig(10175,1,"Giúp các doanh nghiệp định hình và đánh giá tiếp cận các nguồn tài chính mới","Help identify businesses and assess access to new financing","lblGiupCacDoanhNghiepDinhHinh"),
            new LanguageConfig(10176,1,"Công cụ đánh giá","Survey tool","lblCongCuDanhGia1"),
            new LanguageConfig(10177,1,"Cách bạn có thể truy cập thông tin cá nhân của mình","How you can access your personal information","lblHowUCanAccept"),
            new LanguageConfig(10178,1,"Chúng tôi lưu trữ thông tin cá nhân trên các máy chủ an toàn do chúng tôi và các nhà cung cấp dịch vụ của chúng tôi quản lý và đôi khi các tệp bản in ra giấy được lưu giữ ở một vị trí an toàn ở Úc, Ireland, Mexico và Hoa Kỳ. Thông tin cá nhân mà chúng tôi lưu trữ hoặc truyền tải được bảo vệ bằng các biện pháp kiểm soát truy cập và bảo mật, bao gồm xác thực tên người dùng và mật khẩu, xác thực hai yếu tố và mã hóa dữ liệu nếu thích hợp. Cách bạn có thể truy cập thông tin cá nhân của mình","We store personal information on secure servers that are managed by us and our service providers, and occasionally hard copy files that are kept in a secure location in Australia, Ireland, Mexico and the US. Personal information that we store or transmit is protected by security and access controls, including username and password authentication, two-factor authentication, and data encryption where appropriate. How you can access your personal information","lblNoiDungWebsite4"),
            new LanguageConfig(10179,1,"Bạn cũng có quyền yêu cầu chúng tôi chuyển thông tin cá nhân của bạn (tức là chuyển ở định dạng có cấu trúc, được sử dụng phổ biến và máy có thể đọc được, cho bạn), xóa hoặc hạn chế xử lý thông tin đó. Bạn cũng có quyền phản đối một số quá trình xử lý dựa trên lợi ích hợp pháp của chúng tôi, chẳng hạn như lập hồ sơ mà chúng tôi thực hiện với mục đích tiếp thị trực tiếp và, khi chúng tôi đã yêu cầu bạn đồng ý xử lý dữ liệu của bạn, hãy rút lại sự đồng ý này vì hơn được mô tả đầy đủ dưới đây.","You are also entitled to ask us to port your personal information (i.e. to transfer in a structured, commonly used and machine-readable format, to you), to erase it, or restrict its processing. You also have rights to object to some processing that is based on our legitimate interests, such as profiling that we perform for the purposes of direct marketing, and, where we have asked for your consent to process your data, to withdraw this consent as more fully described below.","lblNoiDungPrivacy1"),
            new LanguageConfig(10180,1,"Các quyền này bị giới hạn trong một số trường hợp - ví dụ: chúng tôi có thể chứng minh rằng chúng tôi có yêu cầu pháp lý để xử lý thông tin cá nhân của bạn. Trong một số trường hợp, điều này có nghĩa là chúng tôi có thể giữ lại một số dữ liệu ngay cả khi bạn rút lại sự đồng ý của mình.","These rights are limited in some situations – for example, we can demonstrate that we have a legal requirement to process your personal information. In some instances, this means that we may retain some data even if you withdraw your consent.","lblNoiDungPrivacy2"),
            new LanguageConfig(10181,1,"Trong trường hợp chúng tôi yêu cầu thông tin cá nhân của bạn tuân thủ các nghĩa vụ pháp lý hoặc hợp đồng, thì việc cung cấp dữ liệu đó là bắt buộc: nếu dữ liệu đó không được cung cấp, thì chúng tôi sẽ không thể quản lý mối quan hệ hợp đồng của chúng tôi với bạn hoặc để đáp ứng các nghĩa vụ đặt ra cho chúng tôi . Trong tất cả các trường hợp khác, việc cung cấp thông tin cá nhân được yêu cầu là tùy chọn.","Where we require your personal information to comply with legal or contractual obligations, then provision of such data is mandatory: if such data is not provided, then we will not be able to manage our contractual relationship with you, or to meet obligations placed on us. In all other cases, provision of requested personal information is optional.","lblNoiDungPrivacy3"),
            new LanguageConfig(10183,1,"Quản lý sự kiện","Management Events","lblQuanLySuKien"),
            new LanguageConfig(10184,1,"Đổi mật khẩu","Change password","lblDoiMatKhau"),
            new LanguageConfig(10185,1,"Trang quản trị","Admin page","lblTrangQuanTri"),
            new LanguageConfig(10186,1,"Đăng xuất","Log out","lblDangXuat"),
            new LanguageConfig(10187,1,"Liên hệ","Contact","lblLienHe"),
            new LanguageConfig(10188,1,"Danh mục","Category","lblDanhMuc"),
            new LanguageConfig(10189,1,"Thông tin chung","General information","lblThongTinChung"),
            new LanguageConfig(10190,1,"Họ và tên","First and last name","lblHoVaTen"),
            new LanguageConfig(10191,1,"Địa chỉ email","Email","lblDiaChiEmail"),
            new LanguageConfig(10192,1,"Nội dung","Content","lblNoiDung"),
            new LanguageConfig(10193,1,"Gửi đi","Send","lblGuiDi"),
            new LanguageConfig(10194,1,"Nhập họ và tên","Enter first and last name","lblNhapHoVaTen"),
            new LanguageConfig(10195,1,"Nhập Email","Enter email","lblNhapEmail"),
            new LanguageConfig(11145,1,"Những tin tức mới nhất về doanh nghiệp tài chính và các tin tức chính sách tài chính chính thống","The latest financial business news and mainstream financial policy news","lblTinTucCarousel"),
            new LanguageConfig(11146,1,"Danh sách các sự kiện nổi bật bạn có thể quan tâm","List of featured events you may be interested in","lblEventCarousel"),
            new LanguageConfig(11147,1,"Các tài liệu trực quan sinh động từ các chuyên gia hàng đầu trong lĩnh vực chuyển đổi số","Vivid visual documents from leading experts in digital transformation","lblThuVienCarousel"),
            new LanguageConfig(11148,1,"Giới thiệu","Introduce","lblGioiThieu"),
            new LanguageConfig(11150,1,"Trang web hỗ trợ của Cổng thông tin","Sub-website of the National","lblIntroductionProjectHeader1"),
            new LanguageConfig(11151,1,"hỗ trợ doanh nghiệp quốc gia","Business Support Portal","lblIntroductionProjectHeader2"),
            new LanguageConfig(11152,1,"Để giúp giải quyết những thách thức này, Cơ quan Phát triển Doanh nghiệp (AED) thuộc Bộ Kế hoạch và Đầu tư (MPI) đang có kế hoạch thiết kế một trang web con của Cổng thông tin hỗ trợ doanh nghiệp quốc gia chứa hoặc liên kết với thông tin tài chính và tư vấn được thiết kế để nâng cao năng lực tiếp cận tài chính của các DNVVN.","To help solve these challenges, the Agency for Enterprise Development (AED) under the Ministry of Planning and Investment (MPI) is planning to design a sub-website of the National Business Support Portal containing or linking to financial information and advice designed to enhance the capacity of SMEs to access finance.","lblProjectIntroductionContent1"),
            new LanguageConfig(11153,1,"Chính phủ Việt Nam đang ban hành một số chính sách và biện pháp để giúp các doanh nghiệp vừa và nhỏ vượt qua khoản nợ do cuộc khủng hoảng Covid 19 gây ra. Nhiều ngân hàng thương mại cũng đã phát hành các sản phẩm tài chính với mục tiêu cung cấp tín dụng mới cho các DNVVN","The GVN is issuing several policies and measures to help the SMEs overcome the debt caused by the Covid 19 crisis. Many commercial banks have also issued financial products with the goal of providing new credit for SMEs.","lblProjectIntroductionContent2"),
            new LanguageConfig(11155,1,"Cộng đồng doanh nghiệp Việt Nam đã bị ảnh hưởng nặng nề bởi COVID-19.","Vietnam's business community has been hit hard by COVID-19.Many business","lblContentBanner"),
            new LanguageConfig(11156,1,"POST-COVID-19 PHỤC HỒI DOANH NGHIỆP","POST-COVID-19 BUSINESS RECOVERY","lblBanner"),
            new LanguageConfig(11157,1,"LƯU TRỮ AN TOÀN VÀ MẠNH MẼ","STAY SAFE WITH STRONG","lblCoverHeaderContent"),
            new LanguageConfig(11158,1,"Cá nhân","individual","lblCaNhan"),
            new LanguageConfig(11159,1,"Doanh nghiệp","Enterprise","lblDoanhNghiep"),
            new LanguageConfig(11160,1,"Tên đăng nhập","Username","lblTenDangNhap1"),
            new LanguageConfig(11161,1,"Nhập tên đăng nhập","Enter username","lblNhapTenDangNhap1"),
            new LanguageConfig(11162,1,"Số điện thoại","Phone number","lblSoDienThoai"),
            new LanguageConfig(11163,1,"Nhập số điện thoại","Enter phone number","lblNhapSoDienThoai"),
            new LanguageConfig(11164,1,"Chứng minh thư","ID Card","lblChungMinhThu"),
            new LanguageConfig(11165,1,"Nhập số chứng minh thư","Enter ID card","lblNhapSoChungMinhThu"),
            new LanguageConfig(11166,1,"Tên doanh nghiệp","Company's name","lblTenDoanhNghiep"),
            new LanguageConfig(11167,1,"Nhập tên doanh nghiệp","Enter company's name","lblNhapTenDoanhNghiep"),
            new LanguageConfig(11168,1,"Số đăng ký kinh doanh","Business registration number","lblSoDangKyKinhDoanh"),
            new LanguageConfig(11169,1,"Nhập số đăng ký kinh doanh","Enter business registration number","lblNhapSoDangKyKinhDoanh"),
            new LanguageConfig(11170,1,"ĐĂNG KÝ TƯ VẤN","PARTICIPATION INSTRUCTONS","lblDangKyTuVan"),
            new LanguageConfig(11171,1,"THÔNG TIN HỖ TRỢ","TROUBLESHOOTING","lblThongTinHoTro"),
            new LanguageConfig(11172,1,"GIẢI ĐÁP THẮC MẮC","SUPPORT INFORMATION","lblGiaiDapThacMac"),
            new LanguageConfig(11173,1,"HƯỚNG DẪN THAM GIA","SIGN UP FOR A CONSULTATION","lblHuongDanThamGia"),
            new LanguageConfig(11174,1,"Ảnh đại diện","Avatar","lblAnhDaiDien"),
            new LanguageConfig(11175,1,"Cập nhật thay đổi","Update changes","lblCapNhatThayDoi"),
            new LanguageConfig(11176,1,"Nhập mật khẩu hiện tại","Enter current password","lblNhapMatKhauHienTai"),
            new LanguageConfig(11177,1,"Mật khẩu mới","New password","lblMatKhauMoi"),
            new LanguageConfig(11178,1,"Nhập mật khẩu mới","Enter new password","lblNhapMatKhauMoi"),
            new LanguageConfig(11179,1,"Nhập lại mật khẩu mới","Re-enter new password","lblNhapLaiMatKhauMoi"),
            new LanguageConfig(11180,1,"SỰ KIỆN ĐÃ ĐĂNG KÝ THAM GIA","EVENT HAS BEEN REGISTERED","lblSuKienDaDangKyThamGia"),
            new LanguageConfig(11181,1,"Chi tiết sự kiện","Event information","lblChiTietSuKien"),

            // thêm 
            new LanguageConfig(12192,1,"Các câu hỏi thường gặp","Frequently Asked Questions","lblFAQ"),

            new LanguageConfig(11186,1,"Xem chi tiết đánh giá","See review details","lblBaiKhaoSatDanhGia"),
            new LanguageConfig(12182,1,"Bài khảo sát đánh giá","Review survey","lblXemChiTietDanhGia"),
            new LanguageConfig(12184,1,"Cảm ơn bạn đã thực hiện đánh giá","Thank you for your review","lblCamOnBanDaThucHienDanhGia"),
            new LanguageConfig(12185,1,"Tổng điểm","Total score","lblTongDiem"),
            new LanguageConfig(12186,1,"Mục đánh giá","Review item","lblMucDanhGIa"),
            new LanguageConfig(12183,1,"Kết quả đánh giá","Evaluation results on","lblKetQuaDanhGia"),
            new LanguageConfig(12185,1,"Điểm của bạn","Your score","lblDiemCuaBan"),
            new LanguageConfig(12188,1,"Đánh giá","Evaluate","lblDanhGia"),
            new LanguageConfig(12189,1,"Chi tiết điểm từng hạng mục","Details of each item's score","lblChiTietDiemTungHangMuc"),
            new LanguageConfig(12190,1,"Nhận định","Overview","lblNhanDinh"),
            new LanguageConfig(12191,1,"Khả năng tiếp cận vốn ngân hàng","Access to bank capital","lblKhaNangTiepCanVonNganHang"),
            new LanguageConfig(12193,1,"Khuyến nghị","Recommended","lblKhuyenNghi"),
            new LanguageConfig(12194,1,"Nếu bạn có thắc mắc hoặc cần hỗ trợ, tư vấn từ các chuyên gia của chúng tôi, xin vui lòng nhấn vào","If you need our support then click","lblHoTroTuPhiaChungToi"),
            new LanguageConfig(12195,1,"đây","here","lblDay"),
            new LanguageConfig(12196,1,"Trở về trang đánh giá","Back to review page","lblTroVeTrangDanhGia"),
            new LanguageConfig(12197,1,"Tỷ trọng","Proportion","lblTyTrong"),
            new LanguageConfig(12197,1,"Tổng điểm tạm tính","Provisional total score","lblTongDiemTamTinh"),
            new LanguageConfig(12197,1,"Xem kết quả đánh giá","View review results","lblXemKetQuaDanhGia"),
            new LanguageConfig(12197,1,"Đăng ký nhận hỗ trợ","Register for support","lblDangKyHoTro"),
            new LanguageConfig(12201,1,"SỔ TAY HƯỚNG DẪN","GUIDE NOTEBOOK","lblSoTayTitle"),
            new LanguageConfig(12202,1,"Tiếp cận các nguồn tài chính cho doanh nghiệp nhỏ và vừa Việt Nam","Access to financial resources for Vietnamese small and medium enterprises","lblSoTayBannerTittle2"),
            new LanguageConfig(12203,1,"TRA CỨU TRỰC TUYẾN","ONLINE LOOKUP","lblTraCuuTrucTuyen"),
            new LanguageConfig(12204,1,"TẢI VỀ SỔ TAY","DOWNLOAD","lblTaiVeSoTay"),
            new LanguageConfig(12205,1,"Lời mở đầu của dự án","Introduction","lblLoiMoDau"),
            new LanguageConfig(12206,1,"Nhằm bảo đảm tính thực tiễn và phù hợp nhất với nhu cầu của các DNNVV, Sổ tay được xây dựng trên cơ sở các nghiên cứu khảo sát khách quan và cập nhật về thực trạng và nhu cầu tiếp cận tài chính của các DNNVV với các chính sách, sản phẩm, dịch vụ tài chính và các nguồn hỗ trợ tài chính khác nhau cho DNNVV từ các tổ chức tài chính tại Việt Nam...","Safe for implementation and best suited to the requirements of SMEs, the handbook is built on the basis of monitoring, surveying and updating on the main implementation and requirements for accessing resources of SMEs with policy and product enterprises. products, financial services and various sources of financial support for SMEs from institutional finance in Vietnam...","lblIntroduction1"),
            new LanguageConfig(12207,1,"Nhằm bảo đảm tính thực tiễn và phù hợp nhất với nhu cầu của các DNNVV, Sổ tay được xây dựng trên cơ sở các nghiên cứu khảo sát khách quan và cập","In order to ensure practicality and best suit the needs of SMEs, the Handbook is built on the basis of objective and up-to-date survey studies.","lblIntroduction2"),
            new LanguageConfig(12208,1,"Cục trưởng","Director","lblCucTruong"),
            new LanguageConfig(12209,1,"Mục tiêu xây dựng","Construction goals","lblMucTieuXayDung"),
            new LanguageConfig(12210,1,"Sổ tay này được xây dựng nhằm hỗ trợ các DNNVV khắc phục một phần những khó khăn vướng mắc trong tiếp cận tài chính. Với cách tiếp cận đơn giản, logic và thực tiễn","This handbook has been developed to assist SMEs in overcoming some of the difficulties in accessing finance. With a simple, logical and practical approach","lblMucTieuXayDungDes"),
            new LanguageConfig(12211,1,"Thông tin các nguồn tài chính","Provide information about key resources","lblMucTieuXayDung1"),
            new LanguageConfig(12212,1,"Cung cấp một cách hệ thống và tương đối đầy đủ thông tin về các nguồn tài chính khác nhau (bao gồm cả các nguồn hỗ trợ tài chính phát triển kinh doanh “xanh”, kinh doanh có trách nhiệm) mà các DNNVV có thể tiếp cận","Provide systematic and relatively complete information about the different sources of finance (including financial support for “green” business development) that SMEs can access. near","lblMucTieuXayDungDes1"),
            new LanguageConfig(12213,1,"Lựa chọn các nguồn tài chính","Guide to choosing the right financial source","lblMucTieuXayDung2"),
            new LanguageConfig(12214,1,"Hướng dẫn doanh nghiệp xác định và lựa chọn tối ưu các nguồn tài chính phù hợp với nhu cầu và mục đích đầu tư","Guide businesses to identify and optimally select financial sources suitable for investment needs and purposes.","lblMucTieuXayDungDes2"),
            new LanguageConfig(12215,1,"Thông tin hồ sơ và các điều kiện vay vốn","Provide information about credit applications","lblMucTieuXayDung3"),
            new LanguageConfig(12216,1,"Cung cấp thông tin về các yêu cầu, điều kiện của các nguồn tài chính, giúp doanh nghiệp chuẩn bị hồ sơ yêu cầu cấp tín dụng phù hợp với yêu cầu của các tổ chức tài chính","Providing information on the requirements and conditions of financial sources, helping businesses prepare credit request documents in accordance with the requirements of financial institutions.","lblMucTieuXayDungDes3"),
            new LanguageConfig(12217,1,"Phương pháp xây dựng","Construction method","lblPhuongPhapXayDung"),
            new LanguageConfig(12218,1,"Sổ tay được xây dựng trên cơ sở các nghiên cứu - khảo sát khách quan, cập nhật về thực trạng và nhu cầu tiếp cận tài chính của các DNNVV với các chính sách, sản phẩm, dịch vụ tài chính; các nguồn hỗ trợ tài chính khác nhau cho DNNVV từ các tổ chức tài chính tại Việt Nam","The handbook is built on the basis of objective and up-to-date research and surveys on the status and needs of SMEs to access finance with financial policies, products and services; Various sources of financial support for SMEs from financial institutions in Vietnam","lblPhuongPhapXayDungDes"),
            new LanguageConfig(12219,1,"Hướng dẫn","Tutorial","lblHuongDan"),
            new LanguageConfig(12220,1,"Sử dụng sổ tay","Notebook","lblSuDungSoTay"),

            new LanguageConfig(12221,1,"Tìm hiểu tổng quan về các tổ chức tài chính cho DNNVV được nêu ở [Mục 1 – Phần 2] của sổ tay. Phần này sẽ giúp doanh nghiệp có bức tranh tổng thể về các tổ chức tài chính hiện nay có các sản phẩm, dịch vụ tài chính cho DNNVV. Trên cơ sở hiểu về bức tranh tổng quan này, DNNVV sẽ mở ra cho mình nhiều lựa chọn hơn trong tiếp cận tài chính phù hợp với nhu cầu vốn của doanh nghiệp","An overview of financial institutions for SMEs is provided in [Section 1 - Section 2] of the handbook. This section will help businesses have an overall picture of financial institutions that currently have financial products and services for SMEs. On the basis of understanding this overview, SMEs will be open to more people to choose from in accessing finance suitable to the capital needs of enterprises","lblBuoc1"),
            new LanguageConfig(12222,1,"Sau đó, Doanh nghiệp sẽ đi theo trình tự các bước được trình bày tại mục 2 – Phần 2 để xác định nguồn tài chính, sản phẩm tài chính cụ thể phù hợp với giai đoạn phát triển và nhu cầu vốn của doanh nghiệp. Đây là nội dung chính của cuốn sổ tay này. Sau khi lựa chọn được nguồn tài chính, sản phẩm tài chính phù hợp, doanh nghiệp sẽ tìm hiểu về đặc điểm cụ thể của sản phẩm cũng như các điều kiện để tiếp cận được với sản phẩm cụ thể. Tên các tổ chức đang cung cấp các sản phẩm doanh nghiệp đã lựa chọn sẽ được tra cứu tại phần này. Ngoài các sản phẩm tài chính chung cho DNNVV, các sản phẩm tài chính ưu tiên cho một số lĩnh vực và đặc thù hoạt động của doanh nghiệp cũng sẽ được trình bày để doanh nghiệp có thể tiếp cận thông tin đến các nguồn ưu tiên cho doanh nghiệp của mình (nếu có)","Then, the Enterprise will follow the sequence of steps presented in Section 2 - Part 2 to determine specific financial sources and financial products suitable to the development stage and capital needs of the enterprise. This is the main content of this handbook. After selecting the appropriate financial source and financial product, the business will learn about the specific characteristics of the product as well as the conditions for accessing a specific product. Names of organizations that are providing selected enterprise products will be looked up in this section. In addition to general financial products for SMEs, priority financial products for a number of areas and specific business operations will also be presented so that businesses can access information to priority sources for businesses. your business (if any)","lblBuoc2"),
            new LanguageConfig(12223,1,"Một số dịch vụ “phi tài chính” cho DNNVV để doanh nghiệp tham khảo được trình bày tại mục 3 – phần 2","Some 'non-financial' services for SMEs for business reference are presented in section 3 - part 2","lblBuoc3"),
            new LanguageConfig(12224,1,"Trong mục 4 – phần 2, Sổ tay sẽ đưa ra một số điểm cần lưu ý hay bài học kinh nghiệm cho các DNNVV trong quá trình tiếp cận tài chính từ các nguồn bên ngoài. Các lưu ý hay bài học được trình bày theo cách so sánh đối chiếu giữa “những lầm hiểu của doanh nghiệp” và “thực tế” trong tiếp cận tài chính để giúp doanh nghiệp có cái nhìn rõ hơn","In section 4 - part 2, the Handbook will give some points to note or lessons learned for SMEs in the process of accessing finance from external sources. Notes or lessons are presented in a way that compares and contrasts 'enterprise's misunderstandings' and 'reality' in financial approach to help businesses have a better view","lblBuoc4"),
            new LanguageConfig(12225,1,"Phần Phụ lục của Sổ tay cung cấp thông tin chi tiết về các tổ chức tài chính để doanh nghiệp có thể tìm hiểu, liên lạc và trao đổi nhằm đáp ứng nhu cầu tài chính. Ngoài ra, mô tả về điều kiện cơ bản chung sẽ giúp doanh nghiệp hiểu và chuẩn bị hồ sơ tiếp cận tài chính cụ thể hơn cũng như mô tả chi tiết một số sản phẩm/dịch vụ tài chính cơ bản của tổ chức tài chính dành cho DNNVV","The Appendix section of the Handbook provides detailed information about financial institutions so that businesses can learn, communicate and communicate to meet their financial needs. In addition, a description of the general basic conditions will help businesses understand and prepare a more specific financial access profile, as well as describe in detail some of the basic financial products/services of the financial institution. for SMEs.","lblBuoc5"),
            new LanguageConfig(12228,1,"THƯ VIỆN","LIBRARY","lblThuVien"),
            new LanguageConfig(12229,1,"Đào tạo cơ bản và nâng cao về tài chính cho doanh nghiệp","Basic and advanced training in corporate finance","lblTitleThuVien"),
             new LanguageConfig(12230,1,"Giúp các chủ doanh nghiệp tiếp cận các kiến thức quản lý tài chính, gia tăng số lượng DN thành công tiếp cận tài chính","Helping business owners access financial management knowledge, increasing the number of successful businesses accessing finance","lblTextThuVien"),
             new LanguageConfig(12231,1,"Truy cập thư viện","Library access","lblTruyCapThuVien"),
              new LanguageConfig(12232,1,"Đánh giá tài chính","Financial Review","lblDanhGiaTaiChinh"),
               new LanguageConfig(12233,1," Công cụ đánh giá khả năng tiếp cận tài chính và tái cấu trúc doanh nghiệp","Tool to assess financial accessibility and corporate restructuring","lblTitleDanhGiaTaiChinh"),
             new LanguageConfig(12234,1,"Công cụ giúp doanh nghiệp chủ động đánh giá nguồn lực tài chính và vấn đê quản trị tài chính","A tool to help businesses proactively assess financial resources and financial management issues","lblTextDanhGiaTaiChinh"),
             new LanguageConfig(12235,1,"Thực hiện đánh giá","Make an assessment","lblThucHienDanhGia"),
             new LanguageConfig(12236,1,"SỔ TAY TÀI CHÍNH","FINANCIAL HANDBOOK","lblSoTayTaiChinh"),
             new LanguageConfig(12237,1,"Bản đồ nguồn tài chính","Financial resource map","lblTitleSoTayTaiChinh"),
             new LanguageConfig(12238,1," Sổ tay chi tiết các nguồn tài chính và các điều kiện tín dụng cho từng nhu cầu tín dụng của doanh nghiệp","A detailed handbook of financial sources and credit conditions for each business's credit needs","lblTextSoTayTaiChinh"),
             new LanguageConfig(12239,1,"Giới thiệu về sổ tay","About the notebook","lblGioiThieuSotay"),
             new LanguageConfig(12240,1,"TIN TỨC - SỰ KIỆN","NEWS - EVENTS","lblTinTucSuKien"),
             new LanguageConfig(12241,1,"Các tin tức, sự kiện kết nối tài chính","Financial connection news and events","lblTitleTinTucSuKien"),
             new LanguageConfig(12242,1,"Mở rộng cơ hội cho DN tiếp cận các nguồn tài chính hiệu quả nhất","Expand opportunities for businesses to access the most effective financial resources","lblTextTinTucSuKien"),
             new LanguageConfig(12243,1,"Tin tức cập nhật","News update","lblTinTucCapNhat"),
             new LanguageConfig(12244,1,"Danh sách sự kiện","List of events","lblDanhSachSuKien"),
             new LanguageConfig(12245,1,"Khóa học đào tạo tài chính kinh tế cơ bản cho doanh nghiệp","Basic economic and financial training for businesses","lblDaoTaoCoBanslide"),
             new LanguageConfig(12246,1,"Khóa học đào tạo tài chính kinh tế nâng cao cho doanh nghiệp","Advance economic and financial training for businesses","lblDaoTaoNangCaoslide"),
             new LanguageConfig(12247,1,"Đào tạo ứng phó tại chỗ cho doanh nghiệp SME","Training for SMEs","lblDaotaoSmeslide"),
             new LanguageConfig(12248,1,"Đăng ký nhận tin","Subcribe for new posts","lblDangkyNhanTin"),
             new LanguageConfig(12249,1,"Tài liệu được biên soạn từ các chuyên gia trong lĩnh vực doanh nghiệp, tài chính","Documents compiled from experts in the fields of business and finance","lblTaiLieuTrucQuanContext"),
             new LanguageConfig(12250,1,"Cung cấp thông tin vô cùng hữu ích cho các doanh nghiệp, đặc biệt là các doanh nghiệp nhỏ và vừa gặp khó khăn trong dịch Covid-19","Provide extremely useful information for businesses, especially small and medium-sized businesses facing difficulties during the Covid-19 epidemic.","lblTimKiemThongTinContext"),
             new LanguageConfig(12251,1,"Các chuyên gia hàng đầu trong lĩnh vực chuyển đổi số thiết kế giao diễn dễ sử dụng","Leading experts in digital transformation area with easy-to-use Design interfaces","lblChuyenGiaHangDauContext"),
             new LanguageConfig(12252,1,"Các chuyên gia hàng đầu cung cấp một lộ trình, hướng đi cùng một nền tảng vô cùng vững chắc, giúp các doanh nghiệp định hình","Leading experts provide a right direction and a solid foundation to help businesses shape","lblTaiChinhVungChacContext"),

               new LanguageConfig(12245,1,"Tìm kiếm","Search","lblSearch"),
                new LanguageConfig(12246,1,"Tìm thấy","Found","lblTimThay"),
                new LanguageConfig(12247,1,"kết quả cho từ khóa","	results for","lblTextResultSearch"),
                new LanguageConfig(12248,1,"Đã xem hết các bài viết","Viewed all posts","lblXemHetBaiViet"),


            new LanguageConfig(12253,1,"Viết nội dung bình luận","Write comment ","lblWriteComment"),
            new LanguageConfig(12254,1,"Gửi bình luận","Send comment ","lblSendComment"),

            new LanguageConfig(12255,1,"Các tổ chức hợp tác và tài trợ:","Sponsoring and Collaborating Organizations:","lblCoSponsoring"),
            new LanguageConfig(12249,1,"CÔNG CỤ TÀI CHÍNH","SURVEY TOOL","lblCongCuTaiChinh1"),
            new LanguageConfig(12250,1,"Giúp doanh nghiệp đánh giá năng lực tài chính nội tại","Helping businesses assess their financial capacity at","lblMieuTaBannerCongCuDanhGia"),
            new LanguageConfig(12251,1,"Cung cấp công cụ để doanh nghiệp Nhỏ và Vừa tự đánh giá năng lực tiếp cận tài chính và khả năng phục hồi và tái cấu trúc.","Provide tools for SMEs to self-assess their financial access and resilience and restructuring.","lblMieuTaChoAnhCongCuDanhGia"),
            new LanguageConfig(12252,1,"Mời doanh nghiệp chọn các bài khảo sát bên dưới để thực hiện đánh giá!","Businesses choose from the surveys below to make an assessment!","lblMoiLamBaiDanhGia"),
            new LanguageConfig(12253, 1, "Ký", "Register", "lblDangKi1"),

        };
        public static LanguageConfig getLanguageConfigByCode(string code)
        {
            LanguageConfig result = new LanguageConfig();
            for (int i = 0; i < arrList.Count; i++)
            {
                if (arrList[i].Code == code)
                {
                    result = arrList[i];
                    break;
                }
            }
            return result;
        }

        public static LanguageConfig getLanguageConfigByCode(string code,string lang)
        {
            LanguageConfig result = new LanguageConfig();
            for (int i = 0; i < arrList.Count; i++)
            {
                if (arrList[i].Code == code)
                {
                    if (lang == "en")
                    {
                        arrList[i].Name = arrList[i].Name2;
                    }
                    else
                    {
                        arrList[i].Name = arrList[i].Description;
                    }
                    result = arrList[i];
                    break;
                }
            }
            return result;
        }
    }
}
